# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Chunk"
license = "MIT"
licenselink = "https://github.com/IxDay/chunk/blob/master/LICENSE.md"
description = ""
homepage = "http://ixday.github.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.80

[author]
  name = "IxDay"
  homepage = "http://ixday.github.io/"

# If porting an existing theme
[original]
  name = "Chunk"
  homepage = "https://chunkdemo.wordpress.com/"
  repo = ""
